# Generated by Django 4.2.7 on 2023-11-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LivingLiquidsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Spirits_Indian_Whiskey',
        ),
    ]
